### ISSUE TITLE
F-Droid Build: No Icon

### ISSUE THREAD

**Issue by SebastianSchildt** [eclipse-kuksa/kuksa-android-companion#51]
**Describe the bug**
Most  Applications in the F-Droid store have an Icon. KUKSA Companion does not

See screenshot 
![1000001220](https://github.com/eclipse-kuksa/kuksa-android-companion/assets/3707124/f0df48dd-5901-44a9-acd6-25970b509081)

And (Feb 5th) also F-Droid page https://f-droid.org/en/packages/org.eclipse.kuksa.companion/

Is this by intention? Or did we miss some metadata?

**Comment by wba2hi** [comment]
The icon used in the store can easily be controlled by the fastlane (https://github.com/eclipse-kuksa/kuksa-android-companion/tree/main/fastlane/metadata/android/en-US <-> https://f-droid.org/de/docs/All_About_Descriptions_Graphics_and_Screenshots/#fastlane-struktur). Means we can easily add it there, without having to make any other changes. Starting with the next release it should be recognized automatically. 

I did not add any icon to the fastlane, because my thinking was, that when no icon was specified the app icon is used automatically.  Seems I was wrong or that the latest format is not supported.
