### ISSUE TITLE
Improve Design of Settings Screen

### ISSUE THREAD

**Issue by wba2hi** [eclipse-kuksa/kuksa-android-companion#56]
**Is your feature request related to a problem? Please describe.**
"Dialog" Buttons for "Cancel" and "OK" might get cut off, if trying to change the port in landscape mode.

**Describe the solution you'd like**
A more sophisticated and general solution for the settings should be chosen to update the settings. Right now depending on the position in the list the buttons may be cut off. 
Showing a real modal dialog which is centered to the screen might make more sense. Or switch the "TextViews" with "EditTexts". 

**Additional context**
- Buttons no longer should be cut off
- Better overall design

**Comment by wba2hi** [comment]
See Screenshot: 

<img width="761" alt="MicrosoftTeams-image" src="https://github.com/eclipse-kuksa/kuksa-android-companion/assets/138565883/d551979d-9aec-4544-a6a1-18e4e9e95c2b">

**Comment by SebastianSchildt** [comment]
Don't want to request additional Features, but this "Connected" bar might be more... delicate...

maybe just a small indication on top of the buttons or something?

**Comment by wba2hi** [comment]
> Don't want to request additional Features, but [...] 

Please do request whenever you have something in mind or let's discuss about additional features

> ... this "Connected" bar might be more... delicate...

The text being to far on the left side is only due to bad cropping of the image when copy & pasting it or do you think it's to big and would just like to have something more subtle?  
In the SDK we added the following icons to demonstrate the dis-/connected state: 
![grafik](https://github.com/eclipse-kuksa/kuksa-android-companion/assets/138565883/d2635c30-7e85-437e-8b51-e82dc3dd778c)

Are these more to your liking? 

However I'm unsure if the icons would be positioned in the NavigationBar. As people have the expectation to be navigated somewhere and not to "do something in the background". We probably also need to figure something out about to show a "loading / connecting" animation while trying to connect after clicking on it while offline.

**Comment by SebastianSchildt** [comment]
Cropping was an issue but generally I think it is quite "in your face". If you are disconnected, certainly you need a clear indicator. For connected it is the question if that much screen estate should be used for this kind of static "Everything is working as expected" information.

But I think, that is maybe nothing related specifically to this ticket (because it was the same in portrait, just less noticeable).

And the answer seems not obvoius/easy. As you said if it is in the toolbar, it is not good of the visual style is the same as for a button.

In the Tesla App, although I think that is not easy/possible to replicate for us, while not connected the 3D avatar of the car is a transparent silhouette.


![IMG_93D5C8434147-1](https://github.com/eclipse-kuksa/kuksa-android-companion/assets/3707124/65b72711-a9ed-4a62-a5d6-4cfa698ca79d)

Just for brainstorming as we already established we are beyond scope for this PR 😄
